name: Rockchip MPP

on:
  workflow_dispatch: {}
  push:
    branches: [main]
#  schedule:
#    - cron: '15 18 * * 5' # 18:15 UTC on Friday

jobs:
  images:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    outputs:
      image: ${{ steps.meta.tags }}

    env:
      DEBIAN_VERSION: bookworm

    steps:
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: milas
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/milas/rkmpp
          flavor: |
            prefix=${{ env.DEBIAN_VERSION }}-
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=schedule,pattern=latest
            type=raw,value=latest,enable={{is_default_branch}}

      - uses: docker/build-push-action@v4
        with:
          push: true
          pull: true
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
          target: os
          build-args: |
            OS_BASE=docker.io/debian:${{ env.DEBIAN_VERSION }}
          # prevent adding basic auth on all requests or non-GitHub git hosts will reject us
          github-token: ''
